/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2017-12-02 11:44:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class 준호병신_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("<meta name=\"generator\" content=\"Jekyll v3.6.0\">\n");
      out.write("\n");
      out.write("<title>IT컨퍼런스</title>\n");
      out.write("\n");
      out.write("<!-- Bootstrap core CSS -->\n");
      out.write("\n");
      out.write("  <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Documentation extras -->\n");
      out.write("\n");
      out.write("<link href=\".css/docs.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Custom styles for this template -->\n");
      out.write("    <link href=\"jumbotron.css\" rel=\"stylesheet\">\n");
      out.write("\t\n");
      out.write("<script>\n");
      out.write("  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n");
      out.write("  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n");
      out.write("  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n");
      out.write("  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');\n");
      out.write("  ga('create', 'UA-146052-10', 'getbootstrap.com');\n");
      out.write("  ga('send', 'pageview');\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("  </head>\n");
      out.write("  \n");
      out.write("\n");
      out.write("  <body>\n");
      out.write("\n");
      out.write("    \n");
      out.write("\t<nav class=\"navbar navbar-expand-md navbar-dark fixed-top bg-dark\">\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">IT컨퍼런스</a>\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarsExampleDefault\" aria-controls=\"navbarsExampleDefault\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("      </button>\n");
      out.write("\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarsExampleDefault\">\n");
      out.write("        <ul class=\"navbar-nav mr-auto\">\n");
      out.write("          <li class=\"nav-item active\">\n");
      out.write("            <a class=\"nav-link\" href=\"#\">IT컨퍼런스 게시판 <span class=\"sr-only\">(current)</span></a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"#\">자유 게시판</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"#\">개발자정보</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link dropdown-toggle\" href=\"http://example.com\" id=\"dropdown01\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">게임</a>\n");
      out.write("            <div class=\"dropdown-menu\" aria-labelledby=\"dropdown01\">\n");
      out.write("              <a class=\"dropdown-item\" href=\"#\">게임설명</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"#\">게임하기</a>\n");
      out.write("              <a class=\"dropdown-item\" href=\"#\">게임개발자</a>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("        <form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("\t\t  <input class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("          <button class=\"btn btn-lg btn-outline-secondary my-2 my-sm-0\" type=\"submit\">Search</button>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</form>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("  \n");
      out.write("</header>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <main class=\"bd-masthead\" id=\"content\" role=\"main\">\n");
      out.write("  \n");
      out.write("  <div class=\"container\">\n");
      out.write("    <div class=\"row align-items-center\">\n");
      out.write("      <div class=\"col-6 mx-auto col-md-6 order-md-2\">\n");
      out.write("        <img class=\"img-fluid mb-3 mb-md-0\" src=\"./images/2.jpeg\" alt=\"\" width=\"1024\" height=\"860\">\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-6 order-md-1 text-center text-md-left pr-md-5\">\n");
      out.write("        <h1 class=\"mb-3 bd-text\">IT컨퍼런스</h1>\n");
      out.write("        <p class=\"lead\">\n");
      out.write("          참가하세요!\n");
      out.write("        </p>\n");
      out.write("        <p class=\"lead mb-4\">\n");
      out.write("         기모 띠!\n");
      out.write("        </p>\n");
      out.write("        <div class=\"d-flex flex-column flex-md-row lead mb-3\">\n");
      out.write("          <a href=\"/docs/4.0/getting-started/introduction/\" class=\"btn btn-lg btn-outline-secondary mb-3 mb-md-0 mr-md-3\" onclick=\"ga('send', 'event', 'Jumbotron actions', 'Get started', 'Get started');\">회원가입하기</a>\n");
      out.write("          <a href=\"/docs/4.0/getting-started/download/\" class=\"btn btn-lg btn-outline-secondary\" onclick=\"ga('send', 'event', 'Jumbotron actions', 'Download', 'Download 4.0.0-beta.2');\">로그인하기</a>\n");
      out.write("        </div>\n");
      out.write("        <p class=\"text-muted mb-0\">\n");
      out.write("          아주 많은 정보를 가지고 있습니다.\n");
      out.write("        </p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("   \n");
      out.write("\t  \n");
      out.write("\t  <div class=\"jumbotron\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <h1 class=\"display-3\">IT컨퍼런스에 참여해보세요!</h1>\n");
      out.write("          <p>게시판으로 접속하면 많은 정보를 얻을수 있습니다.</p>\n");
      out.write("          <p><a class=\"btn btn-dark\" href=\"#\" role=\"button\">게시판으로 &raquo;</a></p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("  \n");
      out.write("</main>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <footer class=\"bd-footer text-muted\">\n");
      out.write("  <div class=\"container-fluid p-3 p-md-5\">\n");
      out.write("    <ul class=\"bd-footer-links\">\n");
      out.write("      <li><a href=\"https://github.com/twbs/bootstrap\">박준호</a></li>\n");
      out.write("      <li><a href=\"https://twitter.com/getbootstrap\">김성재</a></li>\n");
      out.write("      <li><a href=\"/docs/4.0/examples/\">백두산</a></li>\n");
      out.write("      <li><a href=\"/docs/4.0/about/history/\">똑똑이</a></li>\n");
      out.write("    </ul>\n");
      out.write("    <p>열심히 만들었어요 <a href=\"https://twitter.com/mdo\" target=\"_blank\" rel=\"noopener\">@정말?</a> \n");
      out.write("  </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script>window.jQuery || document.write('<script src=\"/assets/js/vendor/jquery-slim.min.js\"><\\/script>')</script>\n");
      out.write("\n");
      out.write("<script src=\".js/popper.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script src=\".js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <script src=\".js/docs.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\".js/ie-emulation-modes-warning.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  Holder.addTheme('gray', {\n");
      out.write("    bg: '#777',\n");
      out.write("    fg: 'rgba(255,255,255,.75)',\n");
      out.write("    font: 'Helvetica',\n");
      out.write("    fontweight: 'normal'\n");
      out.write("  });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
